- draft-enghardt-panrg-path-properties.md
This (really short) Pull Request substitutes the Wireless properties with the more abstract data rates based on RFC 8175.
Also, I substituted "available bandwidth" (capacity) with "maximum data rate" in the process, because it's actually the same thing, just available bandwidth (capacty) is supposed to apply to the entire path instead of just one link.
Now this is the theoretical maximum of all links on the path, which might be different from the actually achievable throughput on this path. But I'm not sure we will be able to specify the actually achievable throughput on a path with the definition of path on a per-packet basis and with flows... maybe the flow can have a maximum throughput later? But that's future work.
In this PR, I'm not sure if we need to reference RFC 8175? It inspires …
> Wireless properties, MTU

- draft-enghardt-panrg-path-properties.md
I went over our property and category definitions and adjusted them to our new terminology.
In the process, PvDs went out of the draft, because they are related to how to get domain properties, not what domain properties exist. But maybe if we find we are missing PvD, we can add it again later.
Also, I realized that several properties relate to both path elements in the same domain and in the backbone. Overall, these categories are quite endpoint-centric, and maybe we want to rethink them at some point - not now though. ;)
> Redefine domain, backbone, and dynamic properties

- draft-enghardt-panrg-path-properties.md
Changed definitions according to the suggestions in #1.
Questions:
- With this, a path is always between two hosts, but a subpath can be between a host and a node. I think this makes sense, as we are talking about "endpoints" (hosts) a lot. Do you agree?
- Is the part about the layering clear enough? I think a single path ultimately consists of just one sequence of path elements, just that some lower-layer path elements are hidden when you, e.g., only look at the transport layer. I'm not sure if "A path is defined on a specific layer" actually conveys this. Ideas? Opinions?
> Fix terminology

- draft-enghardt-panrg-path-properties.md
Now that we've converged on the terminology, I did a first pass on the other sections, see the "adjust-terms" branch. 
Mostly, I replaced "endpoint" with "host" and "path segment" with "subpath". Sometimes I made "path element" more specific, i.e., link or node.
I think these are the minimal changes. Feel free to add more.
> Some terms fixed in other sections

- draft-enghardt-panrg-path-properties.md
This PR updates our terminology in line with feedback from IETF 105 and Med's comments.
See also issue #1.
A node can now be an entire AS -- can a node also be something like an amorphous collection of path elements in case of partial visibililty? (open question)
A property can now also apply to a set of subpaths -- I wanted this because the sequence of path elements on which a packet is sent can change frequently, even if the endpoints stay the same.
Do you agree?
> Change definitions based on feedback

- draft-enghardt-panrg-path-properties.md
This removes the domain/backbone classification, leaving only dynamic and non-dynamic properties.
Right now, dynamic properties relate to the transmission of a specific flow and non-dynamic are everything else - not sure yet if the naming still makes sense this way.
Other ideas for definitions or names?
Anyway, I think that this addresses the remaining comments in #15 and #16.
> Remove domain/backbone classification, address #15 and #16

- draft-enghardt-panrg-path-properties.md
Based on the comments we got at IETF 106 and on Med's review, I refactored the use cases.
I removed Performance Monitoring and Enhancement because monitoring was mostly talking about how to get path properties (which is out of scope for our draft) and then enhancement can take different forms: Path selection, protocol selection/configuration, service invocation, or perhaps others.
Here I'm just wondering whether to include a reference to LOOPS somewhere, e.g., a path element adding some FEC on some encapsulated traffic based on path properties. But we don't really have an adopted draft for that yet, while other examples such as TCP converters and performance routing are already adopted IETF documents.
I reshuffled the Path Selection section a bit because I think the part of when you can …
> Refactor use cases, fix #29

- draft-enghardt-panrg-path-properties.md
I defined transparency as a property of a service function.
I'm not sure if this restricts the usefulness of the transparency property.
Are there cases where transparency is relevant for nodes/links that are not service functions?
Do you have other suggestions how to define it?
> Add transparency property

- draft-enghardt-panrg-path-properties.md
This should cover everything discussed in #23 except the use cases section, which we tackle in another issue.
I added the definitions we promised to add while limiting our scope to definitions, i.e., not trying to go into how paths and path properties can be discovered. That's also why I cut some details for the "Transport Protocols available" property: Sure, a host can cache this because it's visible locally, but also based on probing as Med correctly pointed out, but let's try to avoid going into these different possibilities here.
> Editorial and definition changes based on Med's review of -03

- draft-enghardt-panrg-path-properties.md
Adds a paragraph to Security Considerations to discuss encryption and integrity protection and why we don't need explicit path properties for this.
> Discuss secrecy/integrity protection in the Security Considerations

- draft-irtf-panrg-path-properties.md
Add examples (web browser for client node and web server for server node) to host definition
> Add examples to host definition

- draft-irtf-panrg-path-properties.md
Reference the definition of path awareness in Section 1.1 of the Questions draft.
Also, make the initial statement less general - The current Internet does not support explicit discovery of path properties, but endpoints already do measure some properties of their paths (e.g., RTT measurements in a TCP stack).
> Quote path awareness definition and relationship to this draft

- draft-irtf-panrg-path-properties.md
I added a table for different node behaviors (block, modify, ...) based on different inputs.
I'm not sure if this table is useful/consistent since different actions might have different inputs which cannot be represented in a reasonably small table.
An alternative approach instead of the table would be to add some text which describes the main takeaways from the table, i.e., node might block but not modify, node might modify headers but be transparent to payloads, ...
> Add table for different degrees of transparency

- draft-irtf-panrg-path-properties.md
I defined a path as symmetric only for a given level of abstraction and added IP routing symmetric paths as an example.
But I'm not convinced that covers all cases, as the order might not be relevant for certain service functions as Gorry pointed out.
What we could do is phrase the definition more generally:
"Two paths are symmetric if the path and its reverse path consist of the same path elements on the same level of abstraction, ~~but~~ **typically** in reverse order"
> Consider path as symmetric on a given level of abstraction

- draft-irtf-panrg-path-properties.md
This PR does the following:
- Update the definition of "path aware networking" based on the current questions draft
- In the use cases section and the examples section, clarify how different entities have visibility of and control over different path elements and path properties. (Implicit: This is why the generic definition in this document becomes a specific definition in the context of a specific technology)
- In the Examples section, remove some text around examples that are not really path-aware networking
- Minor editorial fixes
Please let me know what you think.
> Adjust definition to questions draft, rephrase different levels of abstraction

- draft-irtf-panrg-path-properties.md
Based on Brian's comment at IETF 110, setting the context explicitly: We're talking about Service Function Chaining.
> Clarify context of Service Invocation use case, closes #49

- draft-irtf-panrg-path-properties.md
When examining our use of "entity", I found that often we really mean anything that is either a node or measures path properties or processes them and potentially makes decisions based on them, e.g., path selection.
Therefore, I kept "entity" in most places, but added a definition as suggested by Med.
Also chose terms more deliberately in the "Path Selection" section - paths can be selected by any entity, not just the communicating node. And "traffic" is undefined so I substituted it by "flows" when we really just mean flows... or "data" when the packet has not actually been created yet (i.e., before a protocol has been selected).
> Define "entity", be more deliberate in using entity VS node VS host, and traffic VS flows

- draft-irtf-panrg-path-properties.md
As discussed, this PR adds definitions for "endpoint" and "end-to-end", whereby I thought the "end-to-end" definition fits well under the later heading and doesn't need to be under our "core" definitions.
I think all occurrences of "host" can be safely substituted by "endpoint", and indeed should be, because surely a non-host endpoint can perform path selection as well as a host can :slightly_smiling_face: 
In the 0-RTT Transport Converter, "host" and "endpoint" appear to be used as synonyms, so I think it's fine to switch "endpoint" here, too, though we could always go back to using "host", which is an example of an endpoint.
I'm also adding a few more acknowledgments, so now that section includes everyone who has reviewed the doc and made substantial comments in these reviews. Shall we …
> Define "endpoint" and "end-to-end"

- draft-irtf-panrg-path-properties.md
I rephrased the definition of administrative domain and added a definition for routing domain identifier as discussed in #58.
I'm wondering if it may be more elegant to define "routing domain" and then only mention its identifier in this definition:
"A routing domain is an administrative domain, in which all path elements use a common routing protocol to communicate with each other.
The routing domain identifier is a unique identifier of a routing domain.
An example of a routing domain identifier is the globally unique autonomous system number (ASN) as defined in {{RFC1930}}."
What do you think?
> Rephrase administrative domain and add routing domain identifier definition

- draft-irtf-panrg-path-properties.md
Added a new definition Target property and rewrote section 3.1 to refer to this new term (see #69).
Also added a comparison to SLE, SLI, and SLOs with a reference to the IETF network slices draft.
> Add target property definition (fixes #69)

- draft-irtf-panrg-path-properties.md
This clarifies that path selection can be done by the network or the entity requesting a certain target property (see #79)
> clarify that paths can be selected by the network or the endpoints

- draft-irtf-panrg-path-properties.md
Fix #87 - The default case is that we don't do path selection at all. 
What exactly happens then will depend on the context, but I'd say this usually means that a single "default" path is used, which may be statically configured. But I don't think it's necessary to spell this out here.
I am pretty sure that we don't want to compare it to a random selection, because I've often seen cases where the default path is "good" and the alternative path is just unsuitable. In such a case, if you select the path randomly, you'll perform much worse than the default of not doing path selection at all.
> Clarify that the path selection should be better than not selecting a path

- draft-irtf-panrg-path-properties.md
Based on Dave Oran's review comment #91, can we just remove "IP" here to leave it as just "MTU"?
(It turns out that the draft even talks about an "Ethernet MTU" in Section 4...)
> Change "IP MTU" to just "MTU" in the definition

- draft-irtf-panrg-path-properties.md
Clarify the point raised by Dave Oran in #86 - Packets may traverse a different path, but any particular path itself does not change its composition.
This is a strict path definition, and my changes are intended to clarify it, rather than change/add anything to the definition.
In the issue, Med brought up a loose path definition, as related to the [Time-Variant Routing (TVR) proposed WG](https://datatracker.ietf.org/wg/tvr/about/).
Upon further reflection, I wonder if this use case could be accomodated using our current path definition, e.g., if a path gets disrupted, it no longer exists as such (as no packets can be transmitted over it anymore), but a different path may have started to exist.
If this works, I would prefer to keep our path definition as-is, rather than adding a loose …
> Rephrase time-dependent part of path definition
